// <auto-generated />
using System;
using BT.Persistence.Features.HR.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BT.Persistence.Migrations.HR
{
    [DbContext(typeof(HrDBContext))]
    [Migration("20260609013929_AddTenantScopeToEmployeeSequences")]
    partial class AddTenantScopeToEmployeeSequences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BT.Domain.Features.HR.Departments.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Departments_Code");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0194f800-0000-7000-8000-000000000100"),
                            Code = "HR",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "People operations, employee lifecycle, and culture.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Human Resources",
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f800-0000-7000-8000-000000000200"),
                            Code = "FIN",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Finance operations, reporting, controls, and treasury.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Finance",
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f800-0000-7000-8000-000000000300"),
                            Code = "IT",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Platforms, systems administration, security, and support.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Information Technology",
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f800-0000-7000-8000-000000000400"),
                            Code = "LEGAL",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Legal advisory, compliance, contracts, and governance.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Legal",
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f800-0000-7000-8000-000000000500"),
                            Code = "OPS",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Day-to-day operations, service delivery, and process excellence.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Operations",
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.HR.Employees.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasDefaultValue("+254");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNationalNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("IX_Employees_Number");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0194f800-0000-7000-8000-000000000001"),
                            CountryCode = "+254",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            DepartmentId = new Guid("0194f800-0000-7000-8000-000000000100"),
                            Email = "aamodhiambo@gmail.com",
                            FirstName = "Alex",
                            IdNumber = "14042262",
                            IsDeleted = false,
                            LastName = "Odhiambo",
                            ManagerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Number = "EMP-001",
                            PhoneNationalNumber = "798980115",
                            PhoneNumber = "+254798980115",
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f800-0000-7000-8000-000000000002"),
                            CountryCode = "+254",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            DepartmentId = new Guid("0194f800-0000-7000-8000-000000000200"),
                            Email = "allan.alex0803@gmail.com",
                            FirstName = "Allan",
                            IdNumber = "67532424",
                            IsDeleted = false,
                            LastName = "Alex",
                            ManagerId = new Guid("0194f800-0000-7000-8000-000000000001"),
                            Number = "EMP-002",
                            PhoneNationalNumber = "700057578",
                            PhoneNumber = "+254700057578",
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("0194f800-0000-7000-8000-000000000003"),
                            CountryCode = "+254",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            DepartmentId = new Guid("0194f800-0000-7000-8000-000000000300"),
                            Email = "omitolaura469@gmail.com",
                            FirstName = "Laura",
                            IdNumber = "76945774",
                            IsDeleted = false,
                            LastName = "Omito",
                            ManagerId = new Guid("0194f800-0000-7000-8000-000000000001"),
                            Number = "EMP-003",
                            PhoneNationalNumber = "719423686",
                            PhoneNumber = "+254719423686",
                            RowVersion = new byte[0],
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.HR.Employees.Entities.EmployeeNumberSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LastNumber")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("TenantId", "DepartmentId", "Year")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeeNumberSequences_TenantId_DepartmentId_Year");

                    b.ToTable("EmployeeNumberSequences", (string)null);
                });

            modelBuilder.Entity("BT.Domain.Features.HR.Employees.Entities.EmployeeNumberSequence", b =>
                {
                    b.HasOne("BT.Domain.Features.HR.Departments.Entities.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}

