// <auto-generated />
using System;
using BT.Persistence.Features.IAM.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BT.Persistence.Migrations.IAM
{
    [DbContext(typeof(IamDBContext))]
    [Migration("20260602104152_HardenIamScopeAndMenus")]
    partial class HardenIamScopeAndMenus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BT.Domain.Features.IAM.Menus.Entities.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("RequiredPermissionKey")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("UX_MenuItems_Key");

                    b.HasIndex("Placement", "ParentId", "DepartmentId", "Title")
                        .HasDatabaseName("IX_MenuItems_Placement_Parent_Department_Title");

                    b.ToTable("MenuItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c10101"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Operations dashboard.",
                            Icon = "Dashboard",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "dashboard",
                            Placement = "Sidebar",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Dashboard",
                            Url = "/dashboard"
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c10201"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Administrative workspace.",
                            Icon = "AdminPanelSettings",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "admin-center",
                            Placement = "Sidebar",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Admin Center",
                            Url = "/admin"
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c10301"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Architecture and solution overview.",
                            Icon = "AutoStories",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "solution-overview",
                            Placement = "Sidebar",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Solution Overview",
                            Url = "/overview"
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c20101"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Customer records and onboarding.",
                            Icon = "Business",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "admin-customers",
                            ParentId = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c10201"),
                            Placement = "AdminCenter",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Customers",
                            Url = "/admin/customers"
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c20102"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Department catalog and staff grouping.",
                            Icon = "AccountTree",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "admin-departments",
                            ParentId = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c10201"),
                            Placement = "AdminCenter",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Departments",
                            Url = "/admin/departments"
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c20103"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Staff records and system access.",
                            Icon = "Badge",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "admin-employees",
                            ParentId = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c10201"),
                            Placement = "AdminCenter",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Employees",
                            Url = "/admin/employees"
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c20104"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Navigation catalog and menu visibility.",
                            Icon = "MenuOpen",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "admin-menus",
                            ParentId = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c10201"),
                            Placement = "AdminCenter",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Menus",
                            Url = "/admin/menus"
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c20105"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Permission catalog and access keys.",
                            Icon = "LockPerson",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "admin-permissions",
                            ParentId = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c10201"),
                            Placement = "AdminCenter",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Permissions",
                            Url = "/admin/permissions"
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c20106"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Role catalog and assignments.",
                            Icon = "AdminPanelSettings",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "admin-roles",
                            ParentId = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c10201"),
                            Placement = "AdminCenter",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Roles",
                            Url = "/admin/roles"
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c20107"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Platform configuration surface.",
                            Icon = "Settings",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "admin-settings",
                            ParentId = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c10201"),
                            Placement = "AdminCenter",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Settings",
                            Url = "/admin/settings"
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c20108"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Trusted device review and revocation.",
                            Icon = "Devices",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "admin-user-devices",
                            ParentId = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c10201"),
                            Placement = "AdminCenter",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "User Devices",
                            Url = "/admin/user-devices"
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c20109"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Create accounts and manage lifecycle.",
                            Icon = "Group",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "admin-users",
                            ParentId = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9c10201"),
                            Placement = "AdminCenter",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Users",
                            Url = "/admin/users"
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.IAM.Permissions.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_Permissions_DepartmentId");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("UX_Permissions_Key");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10101"),
                            Action = "view",
                            Context = "IAM",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "View application users.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "users.view",
                            Resource = "users",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10102"),
                            Action = "create",
                            Context = "IAM",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Create application users.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "users.create",
                            Resource = "users",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10103"),
                            Action = "edit",
                            Context = "IAM",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Update application users.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "users.edit",
                            Resource = "users",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10104"),
                            Action = "deactivate",
                            Context = "IAM",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Deactivate application users.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "users.deactivate",
                            Resource = "users",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10105"),
                            Action = "manage_roles",
                            Context = "IAM",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Manage user role assignments.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "users.manage_roles",
                            Resource = "users",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10106"),
                            Action = "manage_permissions",
                            Context = "IAM",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Manage direct user permissions.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "users.manage_permissions",
                            Resource = "users",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10201"),
                            Action = "view",
                            Context = "IAM",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "View platform roles.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "roles.view",
                            Resource = "roles",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10202"),
                            Action = "create",
                            Context = "IAM",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Create platform roles.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "roles.create",
                            Resource = "roles",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10203"),
                            Action = "edit",
                            Context = "IAM",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Update platform roles.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "roles.edit",
                            Resource = "roles",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10204"),
                            Action = "delete",
                            Context = "IAM",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Delete platform roles.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "roles.delete",
                            Resource = "roles",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10205"),
                            Action = "manage_permissions",
                            Context = "IAM",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Manage role permission assignments.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "roles.manage_permissions",
                            Resource = "roles",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10301"),
                            Action = "view",
                            Context = "HR",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "View departments.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "departments.view",
                            Resource = "departments",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10302"),
                            Action = "create",
                            Context = "HR",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Create departments.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "departments.create",
                            Resource = "departments",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10303"),
                            Action = "edit",
                            Context = "HR",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Update departments.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "departments.edit",
                            Resource = "departments",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10304"),
                            Action = "delete",
                            Context = "HR",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Delete departments.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "departments.delete",
                            Resource = "departments",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10401"),
                            Action = "view",
                            Context = "HR",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "View employees.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "employees.view",
                            Resource = "employees",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10402"),
                            Action = "create",
                            Context = "HR",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Create employees.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "employees.create",
                            Resource = "employees",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10403"),
                            Action = "edit",
                            Context = "HR",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Update employees.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "employees.edit",
                            Resource = "employees",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10404"),
                            Action = "delete",
                            Context = "HR",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Delete employees.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "employees.delete",
                            Resource = "employees",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10501"),
                            Action = "view",
                            Context = "Banking",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "View customers.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "customers.view",
                            Resource = "customers",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10502"),
                            Action = "create",
                            Context = "Banking",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Create customers.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "customers.create",
                            Resource = "customers",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10503"),
                            Action = "edit",
                            Context = "Banking",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Update customers.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "customers.edit",
                            Resource = "customers",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10504"),
                            Action = "delete",
                            Context = "Banking",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Delete customers.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "customers.delete",
                            Resource = "customers",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10601"),
                            Action = "view",
                            Context = "Platform",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "View menu catalog.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "menus.view",
                            Resource = "menus",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10602"),
                            Action = "create",
                            Context = "Platform",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Create menu items.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "menus.create",
                            Resource = "menus",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10603"),
                            Action = "edit",
                            Context = "Platform",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Update menu items.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "menus.edit",
                            Resource = "menus",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("018fd81d-2c94-7ad0-a4a3-f1edb9b10604"),
                            Action = "delete",
                            Context = "Platform",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Delete menu items.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "menus.delete",
                            Resource = "menus",
                            RowVersion = new byte[0],
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.IAM.Users.Entities.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_AspNetRoles_DepartmentId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_AspNetRoles_IsDeleted");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("BT.Domain.Features.IAM.Users.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ActivatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeactivatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastFailedLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PasswordLastChanged")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequirePasswordChange")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TotpSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("IX_AppUsers_CustomerId")
                        .HasFilter("[CustomerId] IS NOT NULL");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("IX_AppUsers_EmployeeId")
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_AppUsers_TenantId");

                    b.HasIndex("TenantId", "IsActive", "IsDeleted")
                        .HasDatabaseName("IX_AppUsers_TenantId_IsActive_IsDeleted");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BT.Domain.Features.IAM.Users.Entities.AppUserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceFingerprint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("TrustedUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId", "DeviceFingerprint")
                        .IsUnique()
                        .HasDatabaseName("IX_AppUserDevices_AppUserId_DeviceFingerprint");

                    b.HasIndex("AppUserId", "IsTrusted", "TrustedUntil")
                        .HasDatabaseName("IX_AppUserDevices_AppUserId_IsTrusted_TrustedUntil");

                    b.ToTable("AppUserDevices", (string)null);
                });

            modelBuilder.Entity("BT.Domain.Features.IAM.Users.Entities.AppUserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MobileNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TelephoneNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_AppUserProfiles_AppUserId")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("AppUserProfiles", (string)null);
                });

            modelBuilder.Entity("BT.Domain.Features.IAM.Users.Entities.AppUserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceFingerprint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EndReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastAccessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId", "DeviceFingerprint", "IsActive")
                        .HasDatabaseName("IX_AppUserSessions_AppUserId_DeviceFingerprint_IsActive");

                    b.HasIndex("AppUserId", "IsActive", "ExpiresAt")
                        .HasDatabaseName("IX_AppUserSessions_AppUserId_IsActive_ExpiresAt");

                    b.HasIndex("IsActive", "IsRevoked", "ExpiresAt")
                        .HasDatabaseName("IX_AppUserSessions_IsActive_IsRevoked_ExpiresAt");

                    b.ToTable("AppUserSessions", (string)null);
                });

            modelBuilder.Entity("BT.Domain.Features.IAM.Users.Entities.AppUserTotpSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptedSecret")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId", "IsActive", "ExpiresAt")
                        .HasDatabaseName("IX_AppUserTotpSecrets_AppUserId_IsActive_ExpiresAt");

                    b.ToTable("AppUserTotpSecrets", (string)null);
                });

            modelBuilder.Entity("BT.Domain.Features.IAM.Users.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TokenFamily")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_Token");

                    b.HasIndex("TokenFamily", "AppUserId")
                        .HasDatabaseName("IX_RefreshTokens_TokenFamily_AppUserId");

                    b.HasIndex("AppUserId", "ExpiresAt", "RevokedAt")
                        .HasDatabaseName("IX_RefreshTokens_AppUserId_ExpiresAt_RevokedAt");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("BT.Domain.Features.IAM.Users.Entities.TempTotpSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EncryptedSecret")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsDeleted", "ExpiresAt")
                        .HasDatabaseName("IX_TempTotpSecrets_UserId_IsDeleted_ExpiresAt");

                    b.ToTable("TempTotpSecrets", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BT.Domain.Features.IAM.Users.Entities.AppUserDevice", b =>
                {
                    b.HasOne("BT.Domain.Features.IAM.Users.Entities.AppUser", "AppUser")
                        .WithMany("TrustedDevices")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("BT.Domain.Features.IAM.Users.Entities.AppUserProfile", b =>
                {
                    b.HasOne("BT.Domain.Features.IAM.Users.Entities.AppUser", null)
                        .WithOne()
                        .HasForeignKey("BT.Domain.Features.IAM.Users.Entities.AppUserProfile", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BT.Domain.Features.IAM.Users.Entities.AppUserSession", b =>
                {
                    b.HasOne("BT.Domain.Features.IAM.Users.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("BT.Domain.Features.IAM.Users.Entities.AppUserTotpSecret", b =>
                {
                    b.HasOne("BT.Domain.Features.IAM.Users.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("BT.Domain.Features.IAM.Users.Entities.RefreshToken", b =>
                {
                    b.HasOne("BT.Domain.Features.IAM.Users.Entities.AppUser", "AppUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("BT.Domain.Features.IAM.Users.Entities.TempTotpSecret", b =>
                {
                    b.HasOne("BT.Domain.Features.IAM.Users.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("BT.Domain.Features.IAM.Users.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BT.Domain.Features.IAM.Users.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BT.Domain.Features.IAM.Users.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("BT.Domain.Features.IAM.Users.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BT.Domain.Features.IAM.Users.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BT.Domain.Features.IAM.Users.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BT.Domain.Features.IAM.Users.Entities.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("TrustedDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
