// <auto-generated />
using System;
using BT.Persistence.Features.Shared.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BT.Persistence.Migrations.Shared
{
    [DbContext(typeof(SharedDBContext))]
    partial class SharedDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BT.Domain.Features.Banking.Customers.Lookups.CustomerStatusLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_CustomerStatusLookup_Code");

                    b.ToTable("Lkp_CustomerStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Draft",
                            Description = "Draft",
                            DisplayOrder = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            Code = "PendingApproval",
                            Description = "Pending Approval",
                            DisplayOrder = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Code = "Active",
                            Description = "Active",
                            DisplayOrder = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Code = "Suspended",
                            Description = "Suspended",
                            DisplayOrder = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Code = "Closed",
                            Description = "Closed",
                            DisplayOrder = 5,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.Banking.Customers.Lookups.CustomerTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_CustomerTypeLookup_Code");

                    b.ToTable("Lkp_CustomerTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Individual",
                            Description = "Individual",
                            DisplayOrder = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Code = "Corporate",
                            Description = "Corporate",
                            DisplayOrder = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Code = "Institutional",
                            Description = "Institutional",
                            DisplayOrder = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Code = "SmallMediumEnterprise",
                            Description = "Small & Medium Enterprise",
                            DisplayOrder = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            Code = "Enterprise",
                            Description = "Enterprise",
                            DisplayOrder = 5,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.Banking.Customers.Lookups.DirectorRelationTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_DirectorRelationTypeLookup_Code");

                    b.ToTable("Lkp_DirectorRelationTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Director",
                            Description = "Director",
                            DisplayOrder = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Code = "Shareholder",
                            Description = "Shareholder",
                            DisplayOrder = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Code = "Signatory",
                            Description = "Signatory",
                            DisplayOrder = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Code = "BeneficialOwner",
                            Description = "Beneficial Owner",
                            DisplayOrder = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            Code = "Guarantor",
                            Description = "Guarantor",
                            DisplayOrder = 5,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.Banking.Customers.Lookups.IdentificationTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_IdentificationTypeLookup_Code");

                    b.ToTable("Lkp_IdentificationTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CertificateOfIncorporation",
                            Description = "Certificate of Incorporation",
                            DisplayOrder = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Code = "TIN",
                            Description = "Tax Identification Number",
                            DisplayOrder = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Code = "BusinessLicense",
                            Description = "Business License",
                            DisplayOrder = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Code = "CompanyRegistrationCertificate",
                            Description = "Company Registration Certificate",
                            DisplayOrder = 4,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.Banking.Customers.Lookups.LineOfBusinessLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_LineOfBusinessLookup_Code");

                    b.ToTable("Lkp_LineOfBusiness", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Agriculture",
                            Description = "Agriculture",
                            DisplayOrder = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Code = "Manufacturing",
                            Description = "Manufacturing",
                            DisplayOrder = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Code = "Technology",
                            Description = "Technology",
                            DisplayOrder = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Code = "FinancialServices",
                            Description = "Financial Services",
                            DisplayOrder = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            Code = "Retail",
                            Description = "Retail",
                            DisplayOrder = 5,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            Code = "Services",
                            Description = "Services",
                            DisplayOrder = 6,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            Code = "Proprietary",
                            Description = "Proprietary",
                            DisplayOrder = 7,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            Code = "Trading",
                            Description = "Trading",
                            DisplayOrder = 8,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.Banking.Customers.Lookups.SegmentTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_SegmentTypeLookup_Code");

                    b.ToTable("Lkp_SegmentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PublicLimitedCompany",
                            Description = "Public Limited Company",
                            DisplayOrder = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Code = "PrivateLimitedCompany",
                            Description = "Private Limited Company",
                            DisplayOrder = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Code = "SoleProprietorship",
                            Description = "Sole Proprietorship",
                            DisplayOrder = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Code = "Corporate",
                            Description = "Corporate",
                            DisplayOrder = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            Code = "Retail",
                            Description = "Retail",
                            DisplayOrder = 5,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            Code = "SME",
                            Description = "Small & Medium Enterprise",
                            DisplayOrder = 6,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            Code = "Individual",
                            Description = "Individual",
                            DisplayOrder = 7,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.Banking.Customers.Lookups.SubSegmentTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_SubSegmentTypeLookup_Code");

                    b.ToTable("Lkp_SubSegmentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Local",
                            Description = "Local",
                            DisplayOrder = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Code = "Multinational",
                            Description = "Multinational",
                            DisplayOrder = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Code = "GovernmentOwned",
                            Description = "Government Owned",
                            DisplayOrder = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Code = "Partnership",
                            Description = "Partnership",
                            DisplayOrder = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            Code = "PrivateLimitedCompany",
                            Description = "Private Limited Company",
                            DisplayOrder = 5,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            Code = "PublicLimitedCompany",
                            Description = "Public Limited Company",
                            DisplayOrder = 6,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            Code = "SoleProprietorship",
                            Description = "Sole Proprietorship",
                            DisplayOrder = 7,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            Code = "NGO",
                            Description = "Non-Governmental Organisation",
                            DisplayOrder = 8,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            Code = "Individual",
                            Description = "Individual",
                            DisplayOrder = 9,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.Shared.EmailTemplates.Entities.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_EmailTemplates_Name")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("EmailTemplates", (string)null);
                });

            modelBuilder.Entity("BT.Domain.Features.Shared.FailedMessages.Entities.FailedMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ErrorStackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("FailedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("IX_FailedMessages_MessageId");

                    b.HasIndex("Status", "IsResolved", "FailedAt")
                        .HasDatabaseName("IX_FailedMessages_Status_IsResolved_FailedAt");

                    b.ToTable("FailedMessages", (string)null);
                });

            modelBuilder.Entity("BT.Domain.Features.Shared.Lookups.Entities.FailedMessageStatusLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_FailedMessageStatusLookup_Code");

                    b.ToTable("Lkp_FailedMessageStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Transient",
                            Description = "Transient",
                            DisplayOrder = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Code = "Permanent",
                            Description = "Permanent",
                            DisplayOrder = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Code = "ManualRetry",
                            Description = "Manual Retry",
                            DisplayOrder = 3,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.Shared.Lookups.Entities.LookupCatalogType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_LookupCatalogTypes_Key");

                    b.ToTable("LookupCatalogTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lifecycle statuses available to customer records.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "CustomerStatus",
                            Label = "Customer statuses"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Classification values used when creating and segmenting customers.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "CustomerType",
                            Label = "Customer types"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Relationship labels used for customer directors and signatories.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "DirectorRelationType",
                            Label = "Director relation types"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Operational statuses for failed message tracking.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "FailedMessageStatus",
                            Label = "Failed message statuses"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Identity document types used across onboarding and verification.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "IdentificationType",
                            Label = "Identification types"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Business line values used by banking and reporting flows.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "LineOfBusiness",
                            Label = "Lines of business"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Primary customer segmentation values.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "SegmentType",
                            Label = "Segment types"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Secondary customer segmentation values.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "SubSegmentType",
                            Label = "Sub-segment types"
                        });
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Received")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[OutboxId] IS NOT NULL");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[InboxMessageId] IS NOT NULL AND [InboxConsumerId] IS NOT NULL");

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.HasIndex("BusName", "Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });
#pragma warning restore 612, 618
        }
    }
}
