<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation">
      <VersionOverride>12.1.1</VersionOverride>
    </PackageReference>
    <PackageReference Include="MediatR">
      <VersionOverride>14.1.0</VersionOverride>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\BT.SharedKernel\BT.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Domain\BT.Domain\BT.Domain.csproj" />
  </ItemGroup>

  

</Project>
