// <auto-generated />
using System;
using BT.Persistence.Features.Shared.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BT.Persistence.Features.Shared.Migrations.PostgreSql
{
    [DbContext(typeof(SharedPostgreSqlDBContext))]
    [Migration("20260730210656_SyncSharedPostgresModel")]
    partial class SyncSharedPostgresModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BT.Domain.Features.Banking.Customers.Lookups.CustomerStatusLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_CustomerStatusLookup_TenantId_Code");

                    b.ToTable("Lkp_CustomerStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Draft",
                            Description = "Draft",
                            DisplayOrder = 1,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 5,
                            Code = "PendingApproval",
                            Description = "Pending Approval",
                            DisplayOrder = 2,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            Code = "Active",
                            Description = "Active",
                            DisplayOrder = 3,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 3,
                            Code = "Suspended",
                            Description = "Suspended",
                            DisplayOrder = 4,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 4,
                            Code = "Closed",
                            Description = "Closed",
                            DisplayOrder = 5,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.Banking.Customers.Lookups.CustomerTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_CustomerTypeLookup_TenantId_Code");

                    b.ToTable("Lkp_CustomerTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Individual",
                            Description = "Individual",
                            DisplayOrder = 1,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            Code = "Corporate",
                            Description = "Corporate",
                            DisplayOrder = 2,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 3,
                            Code = "Institutional",
                            Description = "Institutional",
                            DisplayOrder = 3,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 4,
                            Code = "SmallMediumEnterprise",
                            Description = "Small & Medium Enterprise",
                            DisplayOrder = 4,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 5,
                            Code = "Enterprise",
                            Description = "Enterprise",
                            DisplayOrder = 5,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.Banking.Customers.Lookups.DirectorRelationTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_DirectorRelationTypeLookup_TenantId_Code");

                    b.ToTable("Lkp_DirectorRelationTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Director",
                            Description = "Director",
                            DisplayOrder = 1,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            Code = "Shareholder",
                            Description = "Shareholder",
                            DisplayOrder = 2,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 3,
                            Code = "Signatory",
                            Description = "Signatory",
                            DisplayOrder = 3,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 4,
                            Code = "BeneficialOwner",
                            Description = "Beneficial Owner",
                            DisplayOrder = 4,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 5,
                            Code = "Guarantor",
                            Description = "Guarantor",
                            DisplayOrder = 5,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.Banking.Customers.Lookups.IdentificationTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_IdentificationTypeLookup_TenantId_Code");

                    b.ToTable("Lkp_IdentificationTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CertificateOfIncorporation",
                            Description = "Certificate of Incorporation",
                            DisplayOrder = 1,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            Code = "TIN",
                            Description = "Tax Identification Number",
                            DisplayOrder = 2,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 3,
                            Code = "BusinessLicense",
                            Description = "Business License",
                            DisplayOrder = 3,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 4,
                            Code = "CompanyRegistrationCertificate",
                            Description = "Company Registration Certificate",
                            DisplayOrder = 4,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.Banking.Customers.Lookups.LineOfBusinessLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_LineOfBusinessLookup_TenantId_Code");

                    b.ToTable("Lkp_LineOfBusiness", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Agriculture",
                            Description = "Agriculture",
                            DisplayOrder = 1,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            Code = "Manufacturing",
                            Description = "Manufacturing",
                            DisplayOrder = 2,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 3,
                            Code = "Technology",
                            Description = "Technology",
                            DisplayOrder = 3,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 4,
                            Code = "FinancialServices",
                            Description = "Financial Services",
                            DisplayOrder = 4,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 5,
                            Code = "Retail",
                            Description = "Retail",
                            DisplayOrder = 5,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 6,
                            Code = "Services",
                            Description = "Services",
                            DisplayOrder = 6,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 7,
                            Code = "Proprietary",
                            Description = "Proprietary",
                            DisplayOrder = 7,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 8,
                            Code = "Trading",
                            Description = "Trading",
                            DisplayOrder = 8,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.Banking.Customers.Lookups.SegmentTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_SegmentTypeLookup_TenantId_Code");

                    b.ToTable("Lkp_SegmentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PublicLimitedCompany",
                            Description = "Public Limited Company",
                            DisplayOrder = 1,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            Code = "PrivateLimitedCompany",
                            Description = "Private Limited Company",
                            DisplayOrder = 2,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 3,
                            Code = "SoleProprietorship",
                            Description = "Sole Proprietorship",
                            DisplayOrder = 3,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 4,
                            Code = "Corporate",
                            Description = "Corporate",
                            DisplayOrder = 4,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 5,
                            Code = "Retail",
                            Description = "Retail",
                            DisplayOrder = 5,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 6,
                            Code = "SME",
                            Description = "Small & Medium Enterprise",
                            DisplayOrder = 6,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 7,
                            Code = "Individual",
                            Description = "Individual",
                            DisplayOrder = 7,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.Banking.Customers.Lookups.SubSegmentTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_SubSegmentTypeLookup_TenantId_Code");

                    b.ToTable("Lkp_SubSegmentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Local",
                            Description = "Local",
                            DisplayOrder = 1,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            Code = "Multinational",
                            Description = "Multinational",
                            DisplayOrder = 2,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 3,
                            Code = "GovernmentOwned",
                            Description = "Government Owned",
                            DisplayOrder = 3,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 4,
                            Code = "Partnership",
                            Description = "Partnership",
                            DisplayOrder = 4,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 5,
                            Code = "PrivateLimitedCompany",
                            Description = "Private Limited Company",
                            DisplayOrder = 5,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 6,
                            Code = "PublicLimitedCompany",
                            Description = "Public Limited Company",
                            DisplayOrder = 6,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 7,
                            Code = "SoleProprietorship",
                            Description = "Sole Proprietorship",
                            DisplayOrder = 7,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 8,
                            Code = "NGO",
                            Description = "Non-Governmental Organisation",
                            DisplayOrder = 8,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 9,
                            Code = "Individual",
                            Description = "Individual",
                            DisplayOrder = 9,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.Shared.EmailTemplates.Entities.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_EmailTemplates_Name")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("EmailTemplates", (string)null);
                });

            modelBuilder.Entity("BT.Domain.Features.Shared.FailedMessages.Entities.FailedMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ErrorStackTrace")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("IX_FailedMessages_MessageId");

                    b.HasIndex("Status", "IsResolved", "FailedAt")
                        .HasDatabaseName("IX_FailedMessages_Status_IsResolved_FailedAt");

                    b.ToTable("FailedMessages", (string)null);
                });

            modelBuilder.Entity("BT.Domain.Features.Shared.Lookups.Entities.FailedMessageStatusLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_FailedMessageStatusLookup_TenantId_Code");

                    b.ToTable("Lkp_FailedMessageStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Transient",
                            Description = "Transient",
                            DisplayOrder = 1,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            Code = "Permanent",
                            Description = "Permanent",
                            DisplayOrder = 2,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 3,
                            Code = "ManualRetry",
                            Description = "Manual Retry",
                            DisplayOrder = 3,
                            IsDeleted = false,
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.Shared.Lookups.Entities.LookupCatalogType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("UX_LookupCatalogTypes_TenantId_Key");

                    b.ToTable("LookupCatalogTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lifecycle statuses available to customer records.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "CustomerStatus",
                            Label = "Customer statuses",
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            Description = "Classification values used when creating and segmenting customers.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "CustomerType",
                            Label = "Customer types",
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 3,
                            Description = "Relationship labels used for customer directors and signatories.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "DirectorRelationType",
                            Label = "Director relation types",
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 4,
                            Description = "Operational statuses for failed message tracking.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "FailedMessageStatus",
                            Label = "Failed message statuses",
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 5,
                            Description = "Identity document types used across onboarding and verification.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "IdentificationType",
                            Label = "Identification types",
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 6,
                            Description = "Business line values used by banking and reporting flows.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "LineOfBusiness",
                            Label = "Lines of business",
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 7,
                            Description = "Primary customer segmentation values.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "SegmentType",
                            Label = "Segment types",
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        },
                        new
                        {
                            Id = 8,
                            Description = "Secondary customer segmentation values.",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "SubSegmentType",
                            Label = "Sub-segment types",
                            TenantId = new Guid("0194f700-0000-7000-8000-000000000001")
                        });
                });

            modelBuilder.Entity("BT.Domain.Features.Shared.Payments.Entities.PaymentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerReference")
                        .IsUnique();

                    b.HasIndex("ProviderReference")
                        .HasFilter("ProviderReference IS NOT NULL");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("IdempotencyKey IS NOT NULL");

                    b.ToTable("PaymentRecords", (string)null);
                });

            modelBuilder.Entity("BT.Domain.Features.Shared.TenantSettings.Entities.TenantSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique();

                    b.ToTable("TenantSettings", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("BT.Domain.Features.Shared.Payments.Entities.PaymentRecord", b =>
                {
                    b.OwnsOne("BT.Domain.Shared.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentRecordId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("PaymentRecordId");

                            b1.ToTable("PaymentRecords");

                            b1.WithOwner()
                                .HasForeignKey("PaymentRecordId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });
#pragma warning restore 612, 618
        }
    }
}
